### ISSUE TITLE
Windy API used on unauthorized domain.

### ISSUE THREAD

**Issue by Bassievalk** [santi4488/MMM-windy#6]
Any ideas how I could fix this?

**Comment by PierreLeoFerreira** [comment]
I got this Email last year:

Dear Windy API user,

Since we decided to change our business strategy to focus on B2B opportunities, we regret to inform you that the free Windy API service will be discontinued, effective as of January 1, 2020.

If you’d be prepared to accept an alternative solution, we would like to offer the following three options:

1) Commercial CompaniesIf you use our API for your business, we would be more than happy if you contact our Sales Department. They’ll help you to specify your needs and offer the best solution. More information about available parameters, tutorials, and docs can be found on api4.windy.com.

How to apply:

https://api4.windy.com/contact2) Non-Commercial Institutions (Universities, Foundations)In the case you use our API to run any project with beneficial contribution, which is open-sourced and is not a for-profit project, you can ask for a non-commercial plan. 

How to apply:

send us a cover letter explaining why you should use the API for free, then specify the beneficial contribution, and the purpose of your projectsend us a website where the API runsplease communicate from the official email address of the institution that you represent

contact: api@windy.com

3) IndividualsIn the case that programming is your hobby or passion and our API serves you to hone your skills, we would like to present you with the Windy Plugins. This tool is a bit more challenging for your programming skills, but as a reward, your functionality may be presented in the Windy Plugins Library. For more information follow the docs on Github or feel free to reach out to other plugin developers in our community.

Should you need any further information, please do not hesitate to contact us.

Best regards,

Windy Team
